# Generated by Django 4.1 on 2024-06-15 10:35

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_add',
            field=models.FilePathField(null=True, path=pathlib.PurePosixPath('/Users/artmissg/Documents/Projects/django-course/project-building-blog/personal_blog/../blog/static/blog/images')),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, to='blog.tag'),
        ),
    ]
