# Generated by Django 4.1 on 2024-06-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_add',
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
